### ISSUE TITLE
Receipt validation api method private was made private in 1.13.2

### ISSUE THREAD

**Issue by larryonoff** [adaptyteam/AdaptySDK-iOS#19]
Is there any significant reasons to make it private? We use this method directly at the moment, so we cannot update to 1.13.2.

**Comment by AKyashkin** [comment]
@larryonoff why don't you use products / paywall mechanics and build-in `.makePurchase()` method? Since it has a lot of low level supported features, like: SCA, deferred purchases, interrupted purchases, etc.
It also allows you to generate precise dashboard revenue reports, paywalls conversion rates, etc. 
`.validateReceipt()` method doesn't allow you such things at all.

**Comment by larryonoff** [comment]
> @larryonoff why don't you use products / paywall mechanics and build-in `.makePurchase()` method? Since it has a lot of build-in low level features, like: SCA, deferred purchases, interrupted purchases, etc.
> 
> It also allows you to generate precise dashboard revenue reports, paywalls conversion rates, etc. 
> 
> `.validateReceipt()` method doesn't provide you such things at all, you also have to support interrupted purchases and SCA on your side as well.

Thanks for the explanation. We've revised our code. We have reactive extension of validateReceipt method that never used as result.

As solution we just remove this method.
