### ISSUE TITLE
Add StoreKit 2 `Product` to `AdaptyPaywallProduct`

### ISSUE THREAD

**Issue by RobertDresler** [adaptyteam/AdaptySDK-iOS#72]
Currently there is just `SKProduct` in `AdaptyPaywallProduct `. We want to use StoreKit 2 `Product` instead. I checked that there is already logic (`fetchSK2Products` and `fetchSK2ProductsInSameOrder` methods) for fetching and caching StoreKit 2 Products, so is it possible to add it to `AdaptyPaywallProduct`?

**Comment by x401om** [comment]
Hey @RobertDresler!

Apologies for the delayed response.

Thanks a lot for the issue and the PR. We've taken a good look at what you're suggesting, but unfortunately, we can't merge your PR at the moment. The thing is, the proposed solution might lead to very slow performance of functions since requests to SK1 and SK2 could take a significant amount of time.

If you keep an eye on our updates, you'll see that we're gradually adding support for Store Kit 2 features as needed. However, our main purchase flow still operates through Store Kit 1. I suppose that in the foreseeable future, we might fully transition to the new system, but that would require some pretty serious architectural overhauls within our SDK.

Nevertheless, could you describe why you need access to SK2 product? What's lacking in the existing fields?

**Comment by vladimirDarksy** [comment]
Hey @x401om , any update for this enhancement? Nowadays apple already depreciate StoreKit_V1 with iOS 18. 
<img width="1363" alt="image" src="https://github.com/adaptyteam/AdaptySDK-iOS/assets/151634557/b4655b0d-94d9-446f-b31f-c9cc9c88db87">
https://developer.apple.com/app-store/whats-new/#subscription-updates

So our company wants to understand if you plan to integrate StoreKit_V2 ? Thanks

**Comment by x401om** [comment]
Hey, @vladimirDarksy! We are aware of this deprecation, so no worries here. The original StoreKit is still available and will work, but it will not receive any updates. And yes, we have StoreKit 2 support in our roadmap. Hopefully, it will be done even before the iOS 18 release.

**Comment by x401om** [comment]
Hi @RobertDresler @vladimirDarksy, we’ve released version 3.2.0 with full SK2 support. Now, you can use the [sk2Product](https://github.com/adaptyteam/AdaptySDK-iOS/blob/9168af97758dd9e8dfeaa7366a191192a48f92ba/Sources/StoreKit/Entities/AdaptyProduct.swift#L15) value from AdaptyProduct.
